# Define some colors (R, G, B)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
LIGHTBROWN = (175, 126, 47)

# Game settings
WIDTH = 480
HEIGHT = 480 
FPS = 30
TITLE = "Tilemap Demo"
BGCOLOR = LIGHTBROWN

TILESIZE = 16
GRIDWIDTH = WIDTH // TILESIZE
GRIDHEIGHT = HEIGHT // TILESIZE

# MAIN-MENU Settings
MENU_OPTIONS = ["PLAY", "OPTIONS", "RANKING"]
SELECTED_COLOR_MENU = YELLOW
UNSELECTED_COLOR_MENU = WHITE
MAIN_MENU_BG = LIGHTBROWN
OPTION_TEXT_FONT_SIZE = 60
OPTION_TEXT_FONT_TYPE = "chicken_pie"

# RANKING Settings
RANKING_TITLE_FONT_SIZE = 48
RANKING_TITLE_FONT_TYPE = "chicken_pie"
RANKING_SCORE_FONT_SIZE = 36
RANKING_SCORE_FONT_TYPE = "chicken_pie"
RANKING_FILE_PATH = "../data/ranking.txt"
RANKING_TITLE_COLOR = WHITE

# Sprite folder
SPRITE_FOLDER = "assets/images/sprites"

# Sprite files and paths
PLAYER_HEADIMAGE = "snake-head/sh1.png"
IMAGE_FRUIT = "fruits/f1.png"
IMAGE_BACKGROUND = "backgrounds/bg3.png"
PLAYER_BODYIMAGE = "snake-body/sb1.png"
# PLAYER_TAILIMAGE = "snake-tail/st1.png"